db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/gym_crm
db.username=gym_user
db.password=password

hibernate.packagesToScan=com.gym.crm.entity

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=true
hibernate.format_sql=true